---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - luarocks
    - git
    - libssl-dev

- name: add openresty apt key
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present

- name: add openresty apt repo
  apt_repository:
    repo: deb http://openresty.org/package/ubuntu xenial main
    state: present

- name: update apt cache
  apt:
    update_cache: yes

- name: install openresty
  apt:
    name: openresty
    install_recommends: no
    state: present

- name: install lapis
  luarocks:
    name: lapis
    state: present

- name: create directories and symlinks
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: '{{ item.state }}'
    force: yes
  with_items:
    - { src: null, dest: /var/lib/luna, state: directory }
    - { src: /var/lib/luna/nginx.conf.compiled, dest: /usr/local/openresty/nginx/conf/nginx.conf, state: link }
  notify:
    - restart openresty

- name: enable services
  service:
    name: openresty
    state: started
    enabled: yes
